### ISSUE TITLE
Matching page

### ISSUE THREAD

**Issue by sherryzheng2018** [Project2-Team-5/Coder-Mingle#23]
**approved profile**

Matching user cards contain:

- [x] matching user's profile card (photo and name)

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-a16a2525-7fff-6706-9c5c-9395219004ab"><div dir="ltr" style="margin-left:36pt;" align="left">

Title/Subject
--
Message content
--
Send
--

</div></b>
</body>
</html>

**Comment by Aditya8402** [comment]
hi this is aditya and I am interested in contributing to your project.
And can you suggest some ideas and also the requirements for this part of the project.
